# This is a file to get you started with actions

name: CI

# Controls when workflow will run
on:
  # Triggers the workflow on push or pull requests on stable branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from actions tab
  workflow_dispatch:


#A worfkklow run is made up of one or more jobs that can run sequentially or in parallel jobs
jobs:
  #this workflow contains a single job called "build"
  build:
    #the type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      #Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v2

      #Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
